import { EntitySchema, FieldDef } from '../../shared/forms/field-defs';

export type DynamicFilterValue = string | undefined;

const CODE: FieldDef = { key: 'code', label: 'fields.code', type: 'text', required: true, dir: 'ltr' };
const NAME_EN: FieldDef = { key: 'nameEn', label: 'fields.nameEn', type: 'text', dir: 'ltr' };
const NAME_AR: FieldDef = { key: 'nameAr', label: 'fields.nameAr', type: 'text', dir: 'rtl' };
const TAGS: FieldDef = { key: 'tags', label: 'fields.tags', type: 'tags' };
const NAMED = [CODE, NAME_EN, NAME_AR];

/** All master-data screens are driven by these schemas (fields, columns, filters); no per-entity page code. */
export const ENTITY_SCHEMAS: Record<string, EntitySchema> = {
  buildings: {
    key: 'buildings', endpoint: '/buildings',
    links: [{ path: '/rooms', label: 'entities.rooms' }, { path: '/buildings', label: 'entities.buildings' }, { path: '/travel-times', label: 'entities.travelTimes', feature: 'buildings-travel' }], title: 'entities.buildings', singular: 'Building', icon: 'building', managePermission: 'resources.manage',
    fields: [...NAMED, { key: 'zone', label: 'fields.zone', type: 'text' }],
    columns: [{ key: 'code', label: 'fields.code', kind: 'code' }, { key: 'name', label: 'fields.name', kind: 'name' }, { key: 'zone', label: 'fields.zone' }],
  },
  rooms: {
    key: 'rooms', endpoint: '/rooms',
    links: [{ path: '/rooms', label: 'entities.rooms' }, { path: '/buildings', label: 'entities.buildings' }, { path: '/travel-times', label: 'entities.travelTimes', feature: 'buildings-travel' }], title: 'entities.rooms', singular: 'term:room', icon: 'door', managePermission: 'resources.manage', customFieldEntity: 'Room',
    fields: [...NAMED,
      { key: 'roomTypeId', label: 'fields.roomType', type: 'lookup', lookup: 'room-types', required: true },
      { key: 'capacity', label: 'fields.capacity', type: 'number', required: true, min: 0, default: 30 },
      { key: 'buildingId', label: 'fields.building', type: 'ref', ref: '/buildings' },
      { key: 'equipment', label: 'fields.equipment', type: 'lookupMulti', lookup: 'equipment-tags', valueBy: 'code' }, TAGS],
    columns: [{ key: 'code', label: 'fields.code', kind: 'code' }, { key: 'name', label: 'fields.name', kind: 'name' },
      { key: 'roomTypeId', label: 'fields.roomType', kind: 'lookup', lookup: 'room-types' }, { key: 'capacity', label: 'fields.capacity', kind: 'number' },
      { key: 'buildingId', label: 'fields.building', kind: 'ref', ref: '/buildings' }, { key: 'equipment', label: 'fields.equipment', kind: 'lookupCodes', lookup: 'equipment-tags' }],
    filters: [{ key: 'roomTypeId', label: 'fields.roomType', type: 'lookup', lookup: 'room-types' }, { key: 'buildingId', label: 'fields.building', type: 'ref', ref: '/buildings' }],
  },
  instructors: {
    key: 'instructors', endpoint: '/instructors', title: 'term:instructors', singular: 'term:instructor', icon: 'users', managePermission: 'resources.manage', customFieldEntity: 'Instructor',
    fields: [...NAMED,
      { key: 'instructorTypeId', label: 'fields.instructorType', type: 'lookup', lookup: 'instructor-types', required: true },
      { key: 'email', label: 'fields.email', type: 'text', dir: 'ltr' },
      { key: 'orgUnitId', label: 'term:orgUnit', type: 'ref', ref: '/org-units' },
      { key: 'maxHoursPerDay', label: 'fields.maxHoursPerDay', type: 'number', min: 0, max: 24, step: 0.5 },
      { key: 'maxHoursPerWeek', label: 'fields.maxHoursPerWeek', type: 'number', min: 0, max: 168, step: 0.5 },
      { key: 'personId', label: 'fields.personId', type: 'text', dir: 'ltr', hint: 'hints.personId' },
      { key: 'qualifiedCourseIds', label: 'fields.qualifiedCourses', type: 'refMulti', ref: '/courses' }, TAGS],
    columns: [{ key: 'code', label: 'fields.code', kind: 'code' }, { key: 'name', label: 'fields.name', kind: 'name' },
      { key: 'instructorTypeId', label: 'fields.instructorType', kind: 'lookup', lookup: 'instructor-types' },
      { key: 'maxHoursPerWeek', label: 'fields.maxHoursPerWeek', kind: 'number' }, { key: 'email', label: 'fields.email' }],
    filters: [{ key: 'instructorTypeId', label: 'fields.instructorType', type: 'lookup', lookup: 'instructor-types' }],
  },
  courses: {
    key: 'courses', endpoint: '/courses',
    links: [{ path: '/courses', label: 'term:courses' }, { path: '/sessions', label: 'entities.sessions' }, { path: '/offerings', label: 'entities.offerings' }, { path: '/terms', label: 'entities.terms' }], title: 'term:courses', singular: 'term:course', icon: 'book', managePermission: 'resources.manage', customFieldEntity: 'Course',
    fields: [...NAMED, { key: 'orgUnitId', label: 'term:orgUnit', type: 'ref', ref: '/org-units' },
      { key: 'credits', label: 'fields.credits', type: 'number', min: 0, step: 0.5 }, { key: 'color', label: 'fields.color', type: 'color' }, TAGS],
    columns: [{ key: 'color', label: 'fields.color', kind: 'color' }, { key: 'code', label: 'fields.code', kind: 'code' }, { key: 'name', label: 'fields.name', kind: 'name' },
      { key: 'orgUnitId', label: 'term:orgUnit', kind: 'ref', ref: '/org-units' }, { key: 'tags', label: 'fields.tags', kind: 'tags' }],
    filters: [{ key: 'orgUnitId', label: 'term:orgUnit', type: 'ref', ref: '/org-units' }],
  },
  groups: {
    key: 'groups', endpoint: '/groups', title: 'term:groups', singular: 'term:group', icon: 'cap', managePermission: 'resources.manage', customFieldEntity: 'Group',
    fields: [...NAMED,
      { key: 'groupKindId', label: 'fields.groupKind', type: 'lookup', lookup: 'group-kinds', required: true },
      { key: 'studentCount', label: 'fields.studentCount', type: 'number', required: true, min: 0, default: 30 },
      { key: 'orgUnitId', label: 'term:orgUnit', type: 'ref', ref: '/org-units' },
      { key: 'parentGroupId', label: 'fields.parentGroup', type: 'ref', ref: '/groups' },
      { key: 'homeRoomId', label: 'fields.homeRoom', type: 'ref', ref: '/rooms', feature: 'home-rooms' },
      { key: 'shiftId', label: 'fields.shift', type: 'enum', optionsSource: 'shifts', feature: 'shifts' }, TAGS],
    columns: [{ key: 'code', label: 'fields.code', kind: 'code' }, { key: 'name', label: 'fields.name', kind: 'name' },
      { key: 'groupKindId', label: 'fields.groupKind', kind: 'lookup', lookup: 'group-kinds' }, { key: 'studentCount', label: 'fields.studentCount', kind: 'number' },
      { key: 'parentGroupId', label: 'fields.parentGroup', kind: 'ref', ref: '/groups' }, { key: 'orgUnitId', label: 'term:orgUnit', kind: 'ref', ref: '/org-units' }],
    filters: [{ key: 'groupKindId', label: 'fields.groupKind', type: 'lookup', lookup: 'group-kinds' }, { key: 'orgUnitId', label: 'term:orgUnit', type: 'ref', ref: '/org-units' }],
  },
  terms: {
    key: 'terms', endpoint: '/terms',
    links: [{ path: '/courses', label: 'term:courses' }, { path: '/sessions', label: 'entities.sessions' }, { path: '/offerings', label: 'entities.offerings' }, { path: '/terms', label: 'entities.terms' }], title: 'entities.terms', singular: 'Term', icon: 'calendar', managePermission: 'config.manage',
    fields: [...NAMED, { key: 'startDate', label: 'fields.startDate', type: 'date', required: true }, { key: 'endDate', label: 'fields.endDate', type: 'date', required: true },
      { key: 'isCurrent', label: 'fields.isCurrent', type: 'bool' }, { key: 'calendarDays', label: 'fields.calendarDays', type: 'calendar' }],
    columns: [{ key: 'code', label: 'fields.code', kind: 'code' }, { key: 'name', label: 'fields.name', kind: 'name' }, { key: 'startDate', label: 'fields.startDate' },
      { key: 'endDate', label: 'fields.endDate' }, { key: 'isCurrent', label: 'fields.isCurrent', kind: 'bool' }],
  },
  sessions: {
    key: 'sessions', endpoint: '/sessions',
    links: [{ path: '/courses', label: 'term:courses' }, { path: '/sessions', label: 'entities.sessions' }, { path: '/offerings', label: 'entities.offerings' }, { path: '/terms', label: 'entities.terms' }], title: 'entities.sessions', singular: 'term:session', icon: 'layers', managePermission: 'resources.manage', customFieldEntity: 'Session',
    fields: [
      { key: 'termId', label: 'fields.term', type: 'ref', ref: '/terms', required: true },
      { key: 'courseId', label: 'term:course', type: 'ref', ref: '/courses', required: true },
      { key: 'sessionTypeId', label: 'fields.sessionType', type: 'lookup', lookup: 'session-types', required: true },
      { key: 'durationSlots', label: 'fields.durationSlots', type: 'number', required: true, min: 1, max: 12, default: 1 },
      { key: 'sessionsPerWeek', label: 'fields.sessionsPerWeek', type: 'number', required: true, min: 1, max: 20, default: 1 },
      { key: 'requiredRoomTypeId', label: 'fields.requiredRoomType', type: 'lookup', lookup: 'room-types' },
      { key: 'instructorId', label: 'fields.fixedInstructor', type: 'ref', ref: '/instructors' },
      { key: 'requiredEquipment', label: 'fields.requiredEquipment', type: 'lookupMulti', lookup: 'equipment-tags', valueBy: 'code' },
      { key: 'groupIds', label: 'term:groups', type: 'refMulti', ref: '/groups', required: true },
      { key: 'candidateInstructorIds', label: 'fields.instructorPool', type: 'refMulti', ref: '/instructors', feature: 'instructor-pools' },
      { key: 'weekMask', label: 'fields.weeks', type: 'weekMask', feature: 'week-cycles' },
      { key: 'notes', label: 'fields.notes', type: 'textarea' }, TAGS],
    columns: [{ key: 'courseCode', label: 'fields.code', kind: 'code' }, { key: 'courseId', label: 'term:course', kind: 'ref', ref: '/courses' },
      { key: 'sessionTypeId', label: 'fields.sessionType', kind: 'lookup', lookup: 'session-types' }, { key: 'groupIds', label: 'term:groups', kind: 'refMulti', ref: '/groups' },
      { key: 'instructorId', label: 'term:instructor', kind: 'ref', ref: '/instructors' }, { key: 'sessionsPerWeek', label: 'fields.sessionsPerWeek', kind: 'number' },
      { key: 'durationSlots', label: 'fields.durationSlots', kind: 'number' }],
    filters: [{ key: 'termId', label: 'fields.term', type: 'ref', ref: '/terms' }, { key: 'sessionTypeId', label: 'fields.sessionType', type: 'lookup', lookup: 'session-types' },
      { key: 'groupId', label: 'term:group', type: 'ref', ref: '/groups' }, { key: 'courseId', label: 'term:course', type: 'ref', ref: '/courses' }],
  },
  'travel-times': {
    key: 'travel-times', endpoint: '/travel-times',
    links: [{ path: '/rooms', label: 'entities.rooms' }, { path: '/buildings', label: 'entities.buildings' }, { path: '/travel-times', label: 'entities.travelTimes', feature: 'buildings-travel' }], title: 'entities.travelTimes', singular: 'Travel time', icon: 'arrows', managePermission: 'resources.manage', feature: 'buildings-travel',
    fields: [{ key: 'fromBuildingId', label: 'fields.fromBuilding', type: 'ref', ref: '/buildings', required: true },
      { key: 'toBuildingId', label: 'fields.toBuilding', type: 'ref', ref: '/buildings', required: true },
      { key: 'minutes', label: 'fields.minutes', type: 'number', required: true, min: 0, max: 240, default: 10 }],
    columns: [{ key: 'fromBuildingId', label: 'fields.fromBuilding', kind: 'ref', ref: '/buildings' }, { key: 'toBuildingId', label: 'fields.toBuilding', kind: 'ref', ref: '/buildings' },
      { key: 'minutes', label: 'fields.minutes', kind: 'number' }],
  },
  offerings: {
    key: 'offerings', endpoint: '/offerings',
    links: [{ path: '/courses', label: 'term:courses' }, { path: '/sessions', label: 'entities.sessions' }, { path: '/offerings', label: 'entities.offerings' }, { path: '/terms', label: 'entities.terms' }], title: 'entities.offerings', singular: 'Offering', icon: 'book', managePermission: 'resources.manage',
    fields: [{ key: 'courseId', label: 'term:course', type: 'ref', ref: '/courses', required: true }, { key: 'termId', label: 'fields.term', type: 'ref', ref: '/terms', required: true },
      { key: 'groupIds', label: 'term:groups', type: 'refMulti', ref: '/groups' }, { key: 'notes', label: 'fields.notes', type: 'textarea' }],
    columns: [{ key: 'courseId', label: 'term:course', kind: 'ref', ref: '/courses' }, { key: 'termId', label: 'fields.term', kind: 'ref', ref: '/terms' },
      { key: 'groupIds', label: 'term:groups', kind: 'refMulti', ref: '/groups' }],
  },
  'curriculum-rules': {
    key: 'curriculum-rules', endpoint: '/curriculum-rules', title: 'settings.curriculum.title', singular: 'Curriculum rule', icon: 'book', managePermission: 'config.manage', feature: 'curriculum',
    fields: [
      { key: 'orgUnitId', label: 'term:orgUnit', type: 'ref', ref: '/org-units', required: true },
      { key: 'courseId', label: 'term:course', type: 'ref', ref: '/courses', required: true },
      { key: 'sessionTypeId', label: 'fields.sessionType', type: 'lookup', lookup: 'session-types', required: true },
      { key: 'groupKindId', label: 'fields.groupKind', type: 'lookup', lookup: 'group-kinds' },
      { key: 'sessionsPerWeek', label: 'fields.sessionsPerWeek', type: 'number', required: true, min: 1, max: 20, default: 1 },
      { key: 'durationSlots', label: 'fields.durationSlots', type: 'number', min: 1, max: 12 },
      { key: 'requiredInstructorTypeId', label: 'fields.requiredInstructorType', type: 'lookup', lookup: 'instructor-types' },
      { key: 'requiredRoomTypeId', label: 'fields.requiredRoomType', type: 'lookup', lookup: 'room-types' },
      { key: 'defaultInstructorId', label: 'fields.defaultInstructor', type: 'ref', ref: '/instructors' },
      { key: 'sharedAcrossGroups', label: 'fields.sharedAcrossGroups', type: 'bool', feature: 'shared-sessions' },
      { key: 'isActive', label: 'fields.isActive', type: 'bool', default: true }],
    columns: [{ key: 'orgUnitId', label: 'term:orgUnit', kind: 'ref', ref: '/org-units' }, { key: 'courseId', label: 'term:course', kind: 'ref', ref: '/courses' },
      { key: 'sessionTypeId', label: 'fields.sessionType', kind: 'lookup', lookup: 'session-types' }, { key: 'groupKindId', label: 'fields.groupKind', kind: 'lookup', lookup: 'group-kinds' },
      { key: 'sessionsPerWeek', label: 'fields.sessionsPerWeek', kind: 'number' }, { key: 'defaultInstructorId', label: 'fields.defaultInstructor', kind: 'ref', ref: '/instructors' },
      { key: 'isActive', label: 'fields.isActive', kind: 'bool' }],
    filters: [{ key: 'orgUnitId', label: 'term:orgUnit', type: 'ref', ref: '/org-units' }],
  },
  'custom-fields': {
    key: 'custom-fields', endpoint: '/custom-fields', title: 'settings.customFields.title', singular: 'Custom field', icon: 'tag', managePermission: 'config.manage', feature: 'custom-fields',
    fields: [
      { key: 'entityType', label: 'fields.entityType', type: 'enum', required: true, default: 'Instructor',
        options: ['Instructor', 'Room', 'Course', 'Group', 'Session'].map((v) => ({ value: v, label: `enums.customFieldEntity.${v}` })) },
      { key: 'key', label: 'fields.key', type: 'text', required: true, dir: 'ltr' }, NAME_EN, NAME_AR,
      { key: 'dataType', label: 'fields.dataType', type: 'enum', required: true, default: 'Text',
        options: ['Text', 'Number', 'Boolean', 'Date', 'SingleSelect', 'MultiSelect'].map((v) => ({ value: v, label: `enums.customFieldDataType.${v}` })) },
      { key: 'sortOrder', label: 'fields.sortOrder', type: 'number', default: 0 },
      { key: 'required', label: 'fields.required', type: 'bool' }, { key: 'searchable', label: 'fields.searchable', type: 'bool' },
      { key: 'showInTable', label: 'fields.showInTable', type: 'bool', default: true }, { key: 'importable', label: 'fields.importable', type: 'bool', default: true },
      { key: 'isActive', label: 'fields.isActive', type: 'bool', default: true },
      { key: 'options', label: 'fields.options', type: 'json', hint: 'hints.customFieldOptions', default: [] }],
    columns: [{ key: 'entityType', label: 'fields.entityType', kind: 'enum', enumPrefix: 'enums.customFieldEntity' }, { key: 'key', label: 'fields.key', kind: 'code' },
      { key: 'name', label: 'fields.name', kind: 'name' }, { key: 'dataType', label: 'fields.dataType', kind: 'enum', enumPrefix: 'enums.customFieldDataType' },
      { key: 'required', label: 'fields.required', kind: 'bool' }, { key: 'showInTable', label: 'fields.showInTable', kind: 'bool' }],
    filters: [{ key: 'entityType', label: 'fields.entityType', type: 'enum', options: ['Instructor', 'Room', 'Course', 'Group', 'Session'].map((v) => ({ value: v, label: `enums.customFieldEntity.${v}` })) }],
  },
};
